import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>

    
      <html lang="en" className={cn("font-sans", geist.variable)}>
        <body>
          <Header />
          <main className="p-5">
            {children}
          </main>
          <Toaster toastOptions={{ duration: 1000 }}/>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
